services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: orders_l0
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_user -d orders_l0"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./apps/backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: order_user
      DB_PASSWORD: 12345678
      DB_NAME: orders_l0
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "5000:3000"
    environment:
      - API_URL=http://backend:8080
    depends_on:
      - backend

volumes:
  postgres_data: