basePath: /
definitions:
  models.CombinedData:
    description: Information about the order and nested structures
    properties:
      delivery:
        allOf:
        - $ref: '#/definitions/models.Delivery'
        description: delivery information
      items:
        description: items information
        items:
          $ref: '#/definitions/models.Item'
        type: array
      order:
        allOf:
        - $ref: '#/definitions/models.Order'
        description: Main order information
      payment:
        allOf:
        - $ref: '#/definitions/models.Payment'
        description: payment information
    type: object
  models.Delivery:
    description: delivery information
    properties:
      address:
        type: string
      city:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      phone:
        type: string
      region:
        type: string
      zip:
        type: string
    required:
    - address
    - city
    - email
    - id
    - name
    - phone
    - region
    - zip
    type: object
  models.Item:
    description: Product information
    properties:
      brand:
        type: string
      chrtID:
        type: integer
      id:
        type: string
      name:
        type: string
      nmID:
        type: integer
      orderUID:
        type: string
      price:
        type: integer
      rid:
        type: string
      sale:
        type: integer
      size:
        type: string
      status:
        type: integer
      totalPrice:
        type: integer
      trackNumber:
        type: string
    required:
    - brand
    - chrtID
    - id
    - name
    - nmID
    - orderUID
    - price
    - rid
    - sale
    - size
    - status
    - totalPrice
    - trackNumber
    type: object
  models.Order:
    description: Main order information
    properties:
      customerID:
        type: string
      dateCreated:
        type: string
      deliveryID:
        type: string
      deliveryService:
        type: string
      entry:
        type: string
      internalSignature:
        type: string
      locale:
        type: string
      oofShard:
        type: string
      orderUID:
        type: string
      paymentID:
        type: string
      shardKey:
        type: string
      smID:
        type: integer
      trackNumber:
        type: string
    required:
    - customerID
    - dateCreated
    - deliveryID
    - deliveryService
    - entry
    - locale
    - oofShard
    - orderUID
    - paymentID
    - shardKey
    - smID
    - trackNumber
    type: object
  models.Payment:
    description: payment information
    properties:
      amount:
        type: integer
      bank:
        type: string
      currency:
        type: string
      customFee:
        type: integer
      deliveryCost:
        type: integer
      goodsTotal:
        type: integer
      id:
        type: string
      paymentDT:
        type: integer
      provider:
        type: string
      requestID:
        type: string
      transaction:
        type: string
    required:
    - amount
    - bank
    - currency
    - customFee
    - deliveryCost
    - goodsTotal
    - id
    - paymentDT
    - provider
    - transaction
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for getting order information
  title: L0 API
  version: "1.0"
paths:
  /orders/{orderID}:
    get:
      description: Gets information about an order by its ID
      parameters:
      - description: Order ID
        in: path
        name: orderID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CombinedData'
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Receive an order by ID
swagger: "2.0"
